version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "AKIAIOSFODNN7EXAMPLE"
      MINIO_ROOT_PASSWORD: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  echo-server:
    build:
      context: .  # Dockerfile must be in the current directory
    container_name: echo-server
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ROOT_USER: "AKIAIOSFODNN7EXAMPLE"
      MINIO_ROOT_PASSWORD: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      MINIO_BUCKET: "testbucket"
      MINIO_USE_SSL: false
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - app-network