apiVersion: v1
kind: Service
metadata:
  name: file-store-server-service
spec:
  selector:
    app: file-store-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 9000  # Exposing on localhost:9000
  type: NodePort
