apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-store-server
  template:
    metadata:
      labels:
        app: file-store-server
    spec:
      containers:
        - name: file-store-server
          image: yashsharma1911/file-store:latest
          ports:
            - containerPort: 8080
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_BUCKET
              value: "testbucket"
            - name: MINIO_USE_SSL
              value: "false"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
