apiVersion: v1
kind: Service
metadata:
  name: file-store-server-service
spec:
  selector:
    app: file-store-server
  ports:
    - protocol: TCP
      port: 30000 
      targetPort: 30000 
      nodePort: 30000 
  type: NodePort
