apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          ports:
            - containerPort: 9000
          livenessProbe: # Health check of deployment
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 30       
            failureThreshold: 3       
            timeoutSeconds: 5  
          envFrom:
            - secretRef:
                name: minio-secret 
          volumeMounts:
            - name: minio-data
              mountPath: /data
          command:
            - /bin/bash
            - -c
          args: 
            - minio server /data --console-address :9090
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc 